<?php

use App\Http\Controllers\AdminNotificationController;
use App\Http\Controllers\AdminReactBlogController;
use App\Http\Controllers\AdminReactController;
use App\Http\Controllers\AdminReactCustomerController;
use App\Http\Controllers\AdminReactDesignController;
use App\Http\Controllers\AdminReactNewsLetterController;
use App\Http\Controllers\AdminReactPosController;
use App\Http\Controllers\AdminReactPromotionController;
use App\Http\Controllers\AnnouncementController;
use App\Http\Controllers\LandingPublicApiController;
use App\Http\Controllers\WhatsAppAutomation\AuthController;
use App\Http\Controllers\WhatsAppAutomation\GatewaySessionController;
use Illuminate\Support\Facades\Route;

Route::middleware(['auth'])->group(function () {
    Route::get('/superadmin/whatsapp-automation', [AuthController::class, 'launch'])
        ->name('superadmin.whatsapp.launch');
});

Route::prefix('react-admin-api')->group(function () {
    Route::get('/csrf-token', [AdminReactController::class, 'csrfToken']);
    Route::post('/login', [AdminReactController::class, 'login'])->name('login');
    Route::post('/register/request-otp', [AdminReactController::class, 'registerRequestOtp'])->middleware('guest');
    Route::post('/register/verify-otp', [AdminReactController::class, 'registerVerifyOtp'])->middleware('guest');
    Route::post('/register/resend-otp', [AdminReactController::class, 'registerResendOtp'])->middleware('guest');
    Route::post('/password/request-otp', [AdminReactController::class, 'passwordRequestOtp'])->middleware('guest');
    Route::post('/password/verify-otp', [AdminReactController::class, 'passwordVerifyOtp'])->middleware('guest');
    Route::post('/password/resend-otp', [AdminReactController::class, 'passwordResendOtp'])->middleware('guest');
    Route::post('/password/reset', [AdminReactController::class, 'passwordReset'])->middleware('guest');
    Route::get('/public/branding', [AdminReactController::class, 'publicBranding']);
    Route::get('/public/media-library/file', [AdminReactController::class, 'publicMediaLibraryFile']);

    Route::prefix('public/landing')->group(function () {
        Route::post('/register', [LandingPublicApiController::class, 'register'])->middleware('guest');
        Route::post('/register/resend-otp', [LandingPublicApiController::class, 'registerResendOtp'])->middleware('guest');
        Route::get('/plans', [LandingPublicApiController::class, 'plans']);
        Route::get('/theme', [LandingPublicApiController::class, 'theme']);
        Route::get('/live-client-showcases', [LandingPublicApiController::class, 'liveClientShowcases']);
    });

    Route::middleware(['auth', 'react.entitlement'])->group(function () {
        Route::get('/me', [AdminReactController::class, 'me']);
        Route::get('/dashboard', [AdminReactController::class, 'dashboardOverview']);
        Route::post('/whatsapp/gateway/sessions/create', [GatewaySessionController::class, 'create']);
        Route::get('/whatsapp/gateway/sessions/{tenantId}/status', [GatewaySessionController::class, 'status']);
        Route::get('/whatsapp/gateway/sessions/{tenantId}/qr', [GatewaySessionController::class, 'qr']);
        Route::match(['get', 'post', 'delete'], '/whatsapp/gateway/sessions/{tenantId}/logout', [GatewaySessionController::class, 'logout']);
        Route::get('/admin-staff/dashboard', [AdminReactController::class, 'adminStaffDashboard']);
        Route::get('/superstaff/dashboard', [AdminReactController::class, 'superstaffDashboard']);
        Route::get('/reports/revenue', [\App\Http\Controllers\ReportController::class, 'revenueReport']);
        Route::get('/get/report-data/{section}', [\App\Http\Controllers\ReportController::class, 'adminReport']);
        Route::get('/entitlements', [AdminReactController::class, 'entitlements']);
        Route::get('/stores', [AdminReactController::class, 'stores']);
        Route::get('/products', [AdminReactController::class, 'products']);
        Route::post('/products', [AdminReactController::class, 'productStore']);
        Route::get('/products/{id}', [AdminReactController::class, 'productShow'])->whereNumber('id');
        Route::put('/products/{id}', [AdminReactController::class, 'productUpdate'])->whereNumber('id');
        Route::delete('/products/{id}', [AdminReactController::class, 'productDestroy'])->whereNumber('id');
        Route::get('/catalog/categories', [AdminReactController::class, 'catalogCategories']);
        Route::post('/catalog/categories', [AdminReactController::class, 'catalogCategoryStore']);
        Route::put('/catalog/categories/{id}', [AdminReactController::class, 'catalogCategoryUpdate'])->whereNumber('id');
        Route::delete('/catalog/categories/{id}', [AdminReactController::class, 'catalogCategoryDelete'])->whereNumber('id');
        Route::get('/catalog/brands', [AdminReactController::class, 'catalogBrands']);
        Route::post('/catalog/brands', [AdminReactController::class, 'catalogBrandStore']);
        Route::put('/catalog/brands/{id}', [AdminReactController::class, 'catalogBrandUpdate'])->whereNumber('id');
        Route::delete('/catalog/brands/{id}', [AdminReactController::class, 'catalogBrandDelete'])->whereNumber('id');
        Route::get('/catalog/variants', [AdminReactController::class, 'catalogVariants']);
        Route::post('/catalog/variants', [AdminReactController::class, 'catalogVariantStore']);
        Route::put('/catalog/variants/{type}/{id}', [AdminReactController::class, 'catalogVariantUpdate'])->whereNumber('id');
        Route::post('/catalog/variants/reorder/{type}', [AdminReactController::class, 'catalogVariantReorder']);
        Route::delete('/catalog/variants/{type}/{id}', [AdminReactController::class, 'catalogVariantDelete'])->whereNumber('id');
        Route::get('/media-library', [AdminReactController::class, 'mediaLibraryIndex']);
        Route::get('/media-library/file', [AdminReactController::class, 'mediaLibraryFile']);
        Route::post('/media-library/upload', [AdminReactController::class, 'mediaLibraryUpload']);
        Route::post('/media-library/folders', [AdminReactController::class, 'mediaLibraryCreateFolder']);
        Route::delete('/media-library', [AdminReactController::class, 'mediaLibraryDelete']);
        Route::get('/icon-pack', [AdminReactController::class, 'iconPack']);
        Route::get('/business-categories', [AdminReactController::class, 'businessCategories']);
        Route::get('/currencies', [AdminReactController::class, 'currencies']);
        Route::get('/store-create-meta', [AdminReactController::class, 'storeCreateMeta']);
        Route::get('/store-create-ai-meta', [AdminReactController::class, 'storeCreateAiMeta']);
        Route::post('/store-create-ai-preview', [AdminReactController::class, 'storeCreateAiPreview'])
            ->middleware('long_ai_http');
        Route::get('/store-name-availability', [AdminReactController::class, 'storeNameAvailability']);
        Route::get('/suggest-store-slug', [AdminReactController::class, 'suggestStoreSlug']);
        Route::get('/store-domain-availability', [AdminReactController::class, 'storeDomainAvailability']);
        Route::post('/stores/create', [AdminReactController::class, 'createStore'])
            ->middleware('long_ai_http');
        Route::post('/stores/{id}/activate', [AdminReactController::class, 'activateStore'])->whereNumber('id');
        Route::get('/settings/owner-profile', [AdminReactController::class, 'ownerProfileShow']);
        Route::post('/settings/owner-profile', [AdminReactController::class, 'ownerProfileUpdate']);
        Route::get('/settings/website', [AdminReactController::class, 'websiteSettings']);
        Route::put('/settings/website', [AdminReactController::class, 'websiteSettingsUpdate']);
        Route::post('/settings/website', [AdminReactController::class, 'websiteSettingsUpdate']);
        Route::get('/settings/domains', [AdminReactController::class, 'domainSettings']);
        Route::post('/settings/domains', [AdminReactController::class, 'domainSettingsStore']);
        Route::post('/settings/domains/{id}/activate', [AdminReactController::class, 'domainSettingsActivate'])->whereNumber('id');
        Route::get('/account/payment/packages', [AdminReactController::class, 'paymentPackages']);
        Route::get('/account/payment/addons', [AdminReactController::class, 'paymentAddons']);
        Route::get('/account/payment/domain-search', [AdminReactController::class, 'paymentDomainSearch']);
        Route::get('/account/orders', [AdminReactController::class, 'accountOrders']);
        Route::get('/account/modulus-list', [AdminReactController::class, 'accountModulusList']);
        Route::get('/account/marketing-modulus-list', [AdminReactController::class, 'accountMarketingModulusList']);
        Route::post('/account/modulus/toggle', [AdminReactController::class, 'accountModulusToggle']);
        Route::get('/account/modulus/{id}/config', [AdminReactController::class, 'accountModulusConfig'])->whereNumber('id');
        Route::post('/account/modulus/{id}/config', [AdminReactController::class, 'accountModulusConfig'])->whereNumber('id');
        Route::get('/account/orders/{id}', [AdminReactController::class, 'accountOrderShow'])->whereNumber('id');
        Route::post('/account/orders/{id}/status', [AdminReactController::class, 'accountOrderStatusUpdate'])->whereNumber('id');
        Route::post('/account/orders/{id}/restock', [AdminReactController::class, 'accountOrderRestock'])->whereNumber('id');
        Route::get('/account/return-cancel-orders', [AdminReactController::class, 'accountReturnCancelOrders']);
        Route::post('/account/orders/{id}/address', [AdminReactController::class, 'accountOrderAddressUpdate'])->whereNumber('id');
        Route::post('/account/orders/{id}/details', [AdminReactController::class, 'accountOrderDetailsUpdate'])->whereNumber('id');
        Route::post('/account/orders/{id}/comment', [AdminReactController::class, 'accountOrderCommentUpdate'])->whereNumber('id');
        Route::get('/account/staff', [AdminReactController::class, 'accountStaffList']);
        Route::post('/account/orders/bulk-status', [AdminReactController::class, 'accountOrdersBulkStatusUpdate']);
        Route::get('/account/payment/history', [AdminReactController::class, 'paymentHistory']);
        Route::get('/account/payment/history/{id}/invoice', [AdminReactController::class, 'paymentHistoryInvoice'])->whereNumber('id');
        Route::post('/account/payment/addons/coupon', [AdminReactController::class, 'paymentAddonsCoupon']);
        Route::post('/account/payment/addons/checkout', [AdminReactController::class, 'paymentAddonsCheckout']);
        Route::post('/account/payment/addons/manual-checkout', [AdminReactController::class, 'paymentAddonsManualCheckout']);
        Route::post('/account/payment/addons/due-orders/{id}/update', [AdminReactController::class, 'paymentAddonsDueUpdate'])->whereNumber('id');
        Route::get('/merchant-payment/clients', [AdminReactController::class, 'merchantPaymentClients']);
        Route::post('/merchant-payment/clients/{id}/status', [AdminReactController::class, 'merchantPaymentClientStatus'])->whereNumber('id');
        Route::post('/merchant-payment/clients/{id}/withdraw', [AdminReactController::class, 'merchantPaymentClientWithdraw'])->whereNumber('id');
        Route::get('/superadmin/overview', [AdminReactController::class, 'superadminOverview']);
        Route::post('/superadmin/ai-fill', [AdminReactController::class, 'superadminAiFill']);
        Route::get('/superadmin/clients', [AdminReactController::class, 'superadminClients']);
        Route::get('/superadmin/clients/paid', [AdminReactController::class, 'superadminPaidClients']);
        Route::get('/superadmin/clients/register', [AdminReactController::class, 'superadminRegisterClients']);
        Route::get('/superadmin/clients/landing-page', [AdminReactController::class, 'superadminLandingPageClients']);
        Route::get('/superadmin/clients/activities', [AdminReactController::class, 'superadminClientActivities']);
        Route::get('/superadmin/clients/follow-ups', [AdminReactController::class, 'superadminClientFollowUps']);
        Route::get('/superadmin/clients/{id}', [AdminReactController::class, 'superadminClientShow'])->whereNumber('id');
        Route::post('/superadmin/clients/{id}/quick-comment', [AdminReactController::class, 'superadminClientQuickComment'])->whereNumber('id');
        Route::post('/superadmin/clients/{id}/assign-seller', [AdminReactController::class, 'superadminClientAssignSeller'])->whereNumber('id');
        Route::post('/superadmin/clients/{id}/create-website', [AdminReactController::class, 'superadminClientCreateWebsite'])->whereNumber('id');
        Route::post('/superadmin/clients/comments', [AdminReactController::class, 'superadminClientCommentStore']);
        Route::get('/superadmin/plans-billing/order-plan-request/{paymentStatus?}', [AdminReactController::class, 'superadminOrderPlanRequests']);
        Route::post('/superadmin/plans-billing/order-plan-request/{id}/accept', [AdminReactController::class, 'superadminOrderPlanRequestAccept'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/order-plan-request/{id}/reject', [AdminReactController::class, 'superadminOrderPlanRequestReject'])->whereNumber('id');
        Route::get('/superadmin/plans-billing/modulus-requests', [AdminReactController::class, 'superadminModulusRequests']);
        Route::post('/superadmin/plans-billing/modulus-requests/{id}/accept', [AdminReactController::class, 'superadminModulusRequestAccept'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/modulus-requests/{id}/reject', [AdminReactController::class, 'superadminModulusRequestReject'])->whereNumber('id');
        Route::get('/superadmin/plans-billing/invoice-orders', [AdminReactController::class, 'superadminInvoiceOrders']);
        Route::post('/superadmin/plans-billing/invoice-orders/{id}/accept', [AdminReactController::class, 'superadminInvoiceOrderAccept'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/invoice-orders/{id}/reject', [AdminReactController::class, 'superadminInvoiceOrderReject'])->whereNumber('id');
        Route::get('/superadmin/plans-billing/plans/{planType}', [AdminReactController::class, 'superadminPlansCatalog']);
        Route::get('/superadmin/plans-billing/plans/{planType}/entitlements', [AdminReactController::class, 'superadminPlanEntitlementCatalog']);
        Route::get('/superadmin/plans-billing/plans/{planType}/entitlements/{id}', [AdminReactController::class, 'superadminPlanEntitlementCatalog'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/plans/{planType}', [AdminReactController::class, 'superadminPlanCreate']);
        Route::get('/superadmin/plans-billing/plans/{planType}/{id}', [AdminReactController::class, 'superadminPlanShow'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/plans/{planType}/{id}', [AdminReactController::class, 'superadminPlanUpdate'])->whereNumber('id');
        Route::delete('/superadmin/plans-billing/plans/{planType}/{id}', [AdminReactController::class, 'superadminPlanDelete'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/plans/{planType}/{id}/toggle-status', [AdminReactController::class, 'superadminPlanToggleStatus'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/plans/{planType}/{id}/toggle-trial', [AdminReactController::class, 'superadminPlanToggleTrial'])->whereNumber('id');
        Route::post('/superadmin/plans-billing/plans/{planType}/reorder', [AdminReactController::class, 'superadminPlanReorder']);
        Route::get('/superadmin/addons', [AdminReactController::class, 'superadminAddonsList']);
        Route::post('/superadmin/addons', [AdminReactController::class, 'superadminAddonsStore']);
        Route::post('/superadmin/addons/{id}', [AdminReactController::class, 'superadminAddonsUpdate'])->whereNumber('id');
        Route::post('/superadmin/addons/{id}/toggle-status', [AdminReactController::class, 'superadminAddonsToggleStatus'])->whereNumber('id');
        Route::post('/superadmin/addons/reorder', [AdminReactController::class, 'superadminAddonsReorder']);
        Route::get('/superadmin/modulus', [AdminReactController::class, 'superadminModulusList']);
        Route::post('/superadmin/modulus', [AdminReactController::class, 'superadminModulusStore']);
        Route::post('/superadmin/modulus/{id}', [AdminReactController::class, 'superadminModulusUpdate'])->whereNumber('id');
        Route::post('/superadmin/modulus/{id}/toggle-status', [AdminReactController::class, 'superadminModulusToggleStatus'])->whereNumber('id');
        Route::post('/superadmin/modulus/reorder', [AdminReactController::class, 'superadminModulusReorder']);
        Route::get('/superadmin/access-modes', [AdminReactController::class, 'superadminAccessModesShow']);
        Route::post('/superadmin/access-modes', [AdminReactController::class, 'superadminAccessModesSave']);
        Route::get('/superadmin/settings', [AdminReactController::class, 'superadminSettingsShow']);
        Route::post('/superadmin/settings', [AdminReactController::class, 'superadminSettingsSave']);
        Route::get('/superadmin/settings/currency', [AdminReactController::class, 'superadminSettingsCurrencyList']);
        Route::post('/superadmin/settings/currency', [AdminReactController::class, 'superadminSettingsCurrencyStore']);
        Route::post('/superadmin/settings/currency/{id}', [AdminReactController::class, 'superadminSettingsCurrencyUpdate'])->whereNumber('id');
        Route::post('/superadmin/settings/currency/{id}/toggle-status', [AdminReactController::class, 'superadminSettingsCurrencyToggleStatus'])->whereNumber('id');
        Route::post('/superadmin/settings/currency/{id}/toggle-rate-status', [AdminReactController::class, 'superadminSettingsCurrencyToggleRateStatus'])->whereNumber('id');
        Route::get('/superadmin/settings/store-static-data', [AdminReactController::class, 'superadminSettingsStoreStaticData']);
        Route::post('/superadmin/settings/store-static-data', [AdminReactController::class, 'superadminSettingsStoreStaticDataSave']);
        Route::get('/superadmin/domain-requests', [AdminReactController::class, 'superadminDomainRequests']);
        Route::post('/superadmin/domain-requests/{id}/processing', [AdminReactController::class, 'superadminDomainRequestProcessing'])->whereNumber('id');
        Route::post('/superadmin/domain-requests/{id}/accept', [AdminReactController::class, 'superadminDomainRequestAccept'])->whereNumber('id');
        Route::post('/superadmin/domain-requests/{id}/reject', [AdminReactController::class, 'superadminDomainRequestReject'])->whereNumber('id');
        Route::get('/superadmin/designs', [AdminReactController::class, 'superadminDesigns']);
        Route::get('/superadmin/designs/meta', [AdminReactController::class, 'superadminDesignMeta']);
        Route::get('/superadmin/designs/{id}', [AdminReactController::class, 'superadminDesignShow'])->whereNumber('id');
        Route::post('/superadmin/designs', [AdminReactController::class, 'superadminDesignStore']);
        Route::post('/superadmin/designs/{id}', [AdminReactController::class, 'superadminDesignUpdate'])->whereNumber('id');
        Route::post('/superadmin/designs/bulk', [AdminReactController::class, 'superadminDesignBulkAction']);
        Route::post('/superadmin/designs/{id}/toggle-status', [AdminReactController::class, 'superadminDesignToggleStatus'])->whereNumber('id');
        Route::post('/superadmin/designs/{id}/delete', [AdminReactController::class, 'superadminDesignDelete'])->whereNumber('id');
        Route::get('/superadmin/templates', [AdminReactController::class, 'superadminTemplates']);
        Route::get('/superadmin/templates/meta', [AdminReactController::class, 'superadminTemplateMeta']);
        Route::get('/superadmin/templates/{id}', [AdminReactController::class, 'superadminTemplateShow'])->whereNumber('id');
        Route::post('/superadmin/templates', [AdminReactController::class, 'superadminTemplateStore']);
        Route::post('/superadmin/templates/{id}', [AdminReactController::class, 'superadminTemplateUpdate'])->whereNumber('id');
        Route::post('/superadmin/templates/bulk', [AdminReactController::class, 'superadminTemplateBulkAction']);
        Route::post('/superadmin/templates/{id}/toggle-status', [AdminReactController::class, 'superadminTemplateToggleStatus'])->whereNumber('id');
        Route::post('/superadmin/templates/{id}/position', [AdminReactController::class, 'superadminTemplateUpdatePosition'])->whereNumber('id');
        Route::post('/superadmin/templates/{id}/delete', [AdminReactController::class, 'superadminTemplateDelete'])->whereNumber('id');
        Route::get('/superadmin/icon-pack', [AdminReactController::class, 'superadminIconPackList']);
        Route::get('/superadmin/icon-pack/{id}', [AdminReactController::class, 'superadminIconPackShow'])->whereNumber('id');
        Route::post('/superadmin/icon-pack', [AdminReactController::class, 'superadminIconPackStore']);
        Route::post('/superadmin/icon-pack/{id}', [AdminReactController::class, 'superadminIconPackUpdate'])->whereNumber('id');
        Route::post('/superadmin/icon-pack/{id}/delete', [AdminReactController::class, 'superadminIconPackDelete'])->whereNumber('id');
        Route::post('/superadmin/icon-pack/bulk', [AdminReactController::class, 'superadminIconPackBulkAction']);
        Route::get('/superadmin/business-categories', [AdminReactController::class, 'superadminBusinessCategoryList']);
        Route::get('/superadmin/business-categories/{id}', [AdminReactController::class, 'superadminBusinessCategoryShow'])->whereNumber('id');
        Route::post('/superadmin/business-categories', [AdminReactController::class, 'superadminBusinessCategoryStore']);
        Route::post('/superadmin/business-categories/reorder', [AdminReactController::class, 'superadminBusinessCategoryReorder']);
        Route::post('/superadmin/business-categories/{id}', [AdminReactController::class, 'superadminBusinessCategoryUpdate'])->whereNumber('id');
        Route::post('/superadmin/business-categories/{id}/delete', [AdminReactController::class, 'superadminBusinessCategoryDelete'])->whereNumber('id');
        Route::get('/superadmin/store-default/images', [AdminReactController::class, 'superadminStoreDefaultImageLibrary']);
        Route::post('/superadmin/store-default/images', [AdminReactController::class, 'superadminStoreDefaultImageLibraryStore']);
        Route::put('/superadmin/store-default/images/{id}', [AdminReactController::class, 'superadminStoreDefaultImageLibraryUpdate'])->whereNumber('id');
        Route::delete('/superadmin/store-default/images/{id}', [AdminReactController::class, 'superadminStoreDefaultImageLibraryDelete'])->whereNumber('id');
        Route::get('/superadmin/staff', [AdminReactController::class, 'superadminStaffList']);
        Route::get('/superadmin/staff/meta', [AdminReactController::class, 'superadminStaffMeta']);
        Route::get('/superadmin/staff/{id}', [AdminReactController::class, 'superadminStaffShow'])->whereNumber('id');
        Route::post('/superadmin/staff', [AdminReactController::class, 'superadminStaffStore']);
        Route::post('/superadmin/staff/{id}', [AdminReactController::class, 'superadminStaffUpdate'])->whereNumber('id');
        Route::post('/superadmin/staff/{id}/delete', [AdminReactController::class, 'superadminStaffDelete'])->whereNumber('id');
        Route::post('/superadmin/staff/{id}/toggle-status', [AdminReactController::class, 'superadminStaffToggleStatus'])->whereNumber('id');
        Route::match(['get', 'post'], '/superadmin/sales-support-chat/session', [AuthController::class, 'embeddedSession']);
        Route::get('/superadmin/roles', [AdminReactController::class, 'superadminRoleList']);
        Route::get('/superadmin/roles/{id}', [AdminReactController::class, 'superadminRoleShow'])->whereNumber('id');
        Route::post('/superadmin/roles', [AdminReactController::class, 'superadminRoleStore']);
        Route::post('/superadmin/roles/{id}', [AdminReactController::class, 'superadminRoleUpdate'])->whereNumber('id');
        Route::post('/superadmin/roles/{id}/delete', [AdminReactController::class, 'superadminRoleDelete'])->whereNumber('id');
        Route::post('/superadmin/roles/{id}/permissions', [AdminReactController::class, 'superadminRolePermissionUpdate'])->whereNumber('id');
        Route::post('/logout', [AdminReactController::class, 'logout']);

        Route::get('/notifications', [AdminNotificationController::class, 'indexApi']);
        Route::get('/notifications/{id}', [AdminNotificationController::class, 'showApi']);
        Route::post('/notifications', [AdminNotificationController::class, 'storeApi']);
        Route::put('/notifications/{id}', [AdminNotificationController::class, 'updateApi']);
        Route::post('/notifications/{id}/read', [AdminNotificationController::class, 'markReadApi'])->whereNumber('id');
        Route::post('/notifications/mark-all-read', [AdminNotificationController::class, 'markAllReadApi']);
        Route::delete('/notifications/{id}', [AdminNotificationController::class, 'destroyApi']);
        Route::post('/notifications/bulk-delete', [AdminNotificationController::class, 'bulkDestroyApi']);
        Route::get('/announcements', [AnnouncementController::class, 'indexApi']);
        Route::post('/announcements', [AnnouncementController::class, 'storeApi']);
        Route::put('/announcements/{id}', [AnnouncementController::class, 'updateApi'])->whereNumber('id');
        Route::delete('/announcements/{id}', [AnnouncementController::class, 'destroyApi'])->whereNumber('id');
        Route::post('/announcements/{id}/toggle-status', [AnnouncementController::class, 'toggleStatusApi'])->whereNumber('id');
        Route::post('/announcements/bulk-action', [AnnouncementController::class, 'bulkActionApi']);
        Route::get('/marketing/blogs/meta', [AdminReactBlogController::class, 'meta']);
        Route::get('/marketing/blogs', [AdminReactBlogController::class, 'index']);
        Route::get('/marketing/blogs/{id}', [AdminReactBlogController::class, 'show'])->whereNumber('id');
        Route::post('/marketing/blogs', [AdminReactBlogController::class, 'store']);
        Route::post('/marketing/blogs/{id}', [AdminReactBlogController::class, 'update'])->whereNumber('id');
        Route::delete('/marketing/blogs/{id}', [AdminReactBlogController::class, 'destroy'])->whereNumber('id');
        Route::post('/marketing/blogs/{id}/toggle-status', [AdminReactBlogController::class, 'toggleStatus'])->whereNumber('id');
        Route::post('/marketing/blogs/{id}/position', [AdminReactBlogController::class, 'updatePosition'])->whereNumber('id');
        Route::post('/marketing/blogs/bulk-action', [AdminReactBlogController::class, 'bulkAction']);
        Route::get('/marketing/news-latter', [AdminReactNewsLetterController::class, 'index']);
        Route::delete('/marketing/news-latter/{id}', [AdminReactNewsLetterController::class, 'destroy'])->whereNumber('id');
        Route::post('/marketing/news-latter/bulk-delete', [AdminReactNewsLetterController::class, 'bulkDestroy']);
        Route::get('/marketing/news-latter/export', [AdminReactNewsLetterController::class, 'exportCsv']);
        Route::get('/marketing/coupons', [AdminReactPromotionController::class, 'listCoupons']);
        Route::get('/marketing/coupons/{id}', [AdminReactPromotionController::class, 'showCoupon'])->whereNumber('id');
        Route::post('/marketing/coupons', [AdminReactPromotionController::class, 'storeCoupon']);
        Route::post('/marketing/coupons/{id}', [AdminReactPromotionController::class, 'updateCoupon'])->whereNumber('id');
        Route::delete('/marketing/coupons/{id}', [AdminReactPromotionController::class, 'destroyCoupon'])->whereNumber('id');
        Route::post('/marketing/coupons/{id}/toggle-status', [AdminReactPromotionController::class, 'toggleCouponStatus'])->whereNumber('id');
        Route::post('/marketing/coupons/{id}/position', [AdminReactPromotionController::class, 'updateCouponPosition'])->whereNumber('id');
        Route::post('/marketing/coupons/bulk-action', [AdminReactPromotionController::class, 'bulkCouponAction']);
        Route::get('/marketing/campaigns', [AdminReactPromotionController::class, 'listCampaigns']);
        Route::get('/marketing/campaigns/{id}', [AdminReactPromotionController::class, 'showCampaign'])->whereNumber('id');
        Route::post('/marketing/campaigns', [AdminReactPromotionController::class, 'storeCampaign']);
        Route::post('/marketing/campaigns/{id}', [AdminReactPromotionController::class, 'updateCampaign'])->whereNumber('id');
        Route::delete('/marketing/campaigns/{id}', [AdminReactPromotionController::class, 'destroyCampaign'])->whereNumber('id');
        Route::post('/marketing/campaigns/{id}/toggle-status', [AdminReactPromotionController::class, 'toggleCampaignStatus'])->whereNumber('id');
        Route::post('/marketing/campaigns/{id}/position', [AdminReactPromotionController::class, 'updateCampaignPosition'])->whereNumber('id');
        Route::post('/marketing/campaigns/bulk-action', [AdminReactPromotionController::class, 'bulkCampaignAction']);
        Route::get('/marketing/offers', [AdminReactPromotionController::class, 'listOffers']);
        Route::get('/marketing/offers/{id}', [AdminReactPromotionController::class, 'showOffer'])->whereNumber('id');
        Route::post('/marketing/offers', [AdminReactPromotionController::class, 'storeOffer']);
        Route::post('/marketing/offers/{id}', [AdminReactPromotionController::class, 'updateOffer'])->whereNumber('id');
        Route::delete('/marketing/offers/{id}', [AdminReactPromotionController::class, 'destroyOffer'])->whereNumber('id');
        Route::post('/marketing/offers/{id}/toggle-status', [AdminReactPromotionController::class, 'toggleOfferStatus'])->whereNumber('id');
        Route::post('/marketing/offers/{id}/position', [AdminReactPromotionController::class, 'updateOfferPosition'])->whereNumber('id');
        Route::post('/marketing/offers/bulk-action', [AdminReactPromotionController::class, 'bulkOfferAction']);
        Route::get('/orders/customers', [AdminReactCustomerController::class, 'index']);
        Route::post('/orders/customers', [AdminReactCustomerController::class, 'store']);
        Route::get('/orders/customers/export', [AdminReactCustomerController::class, 'exportCsv']);
        Route::get('/orders/customers/{id}', [AdminReactCustomerController::class, 'show'])->whereNumber('id');
        Route::delete('/orders/customers/{id}', [AdminReactCustomerController::class, 'destroy'])->whereNumber('id');
        Route::post('/orders/customers/{id}/block-toggle', [AdminReactCustomerController::class, 'toggleBlock'])->whereNumber('id');
        Route::post('/orders/customers/bulk-delete', [AdminReactCustomerController::class, 'bulkDestroy']);
        Route::get('/account/orders/courier-fraud/{phone}', [AdminReactController::class, 'accountOrderCourierFraud']);
        Route::get('/inventory/stock-list', [AdminReactController::class, 'inventoryStockList']);
        Route::post('/inventory/stock-list/stock-alert-limit', [AdminReactController::class, 'inventoryStockSetAlertLimit']);
        Route::post('/inventory/stock-list/bulk-action', [AdminReactController::class, 'inventoryStockBulkAction']);
        Route::post('/inventory/stock-list/{id}/toggle-status', [AdminReactController::class, 'inventoryStockToggleStatus'])->whereNumber('id');
        Route::get('/inventory/suppliers', [AdminReactController::class, 'inventorySuppliers']);
        Route::post('/inventory/suppliers', [AdminReactController::class, 'inventorySupplierStore']);
        Route::post('/inventory/suppliers/bulk-delete', [AdminReactController::class, 'inventorySupplierBulkDelete']);
        Route::get('/inventory/suppliers/export', [AdminReactController::class, 'inventorySupplierExport']);
        Route::get('/inventory/suppliers/{id}/products', [AdminReactController::class, 'inventorySupplierProducts'])->whereNumber('id');
        Route::post('/inventory/suppliers/{id}', [AdminReactController::class, 'inventorySupplierUpdate'])->whereNumber('id');
        Route::delete('/inventory/suppliers/{id}', [AdminReactController::class, 'inventorySupplierDelete'])->whereNumber('id');
        Route::get('/staff-access/staff/meta', [AdminReactController::class, 'staffAccessStaffMeta']);
        Route::get('/staff-access/staff', [AdminReactController::class, 'staffAccessStaffList']);
        Route::post('/staff-access/staff', [AdminReactController::class, 'staffAccessStaffStore']);
        Route::post('/staff-access/staff/bulk-delete', [AdminReactController::class, 'staffAccessStaffBulkDelete']);
        Route::get('/staff-access/staff/export', [AdminReactController::class, 'staffAccessStaffExport']);
        Route::post('/staff-access/staff/{id}', [AdminReactController::class, 'staffAccessStaffUpdate'])->whereNumber('id');
        Route::delete('/staff-access/staff/{id}', [AdminReactController::class, 'staffAccessStaffDelete'])->whereNumber('id');
        Route::get('/staff-access/roles/meta', [AdminReactController::class, 'staffAccessRoleMeta']);
        Route::get('/staff-access/roles', [AdminReactController::class, 'staffAccessRoleList']);
        Route::post('/staff-access/roles', [AdminReactController::class, 'staffAccessRoleStore']);
        Route::post('/staff-access/roles/{id}', [AdminReactController::class, 'staffAccessRoleUpdate'])->whereNumber('id');
        Route::post('/staff-access/roles/{id}/permissions', [AdminReactController::class, 'staffAccessRolePermissionsUpdate'])->whereNumber('id');
        Route::delete('/staff-access/roles/{id}', [AdminReactController::class, 'staffAccessRoleDelete'])->whereNumber('id');
        Route::get('/pos/context', [AdminReactPosController::class, 'context']);
        Route::get('/pos/branches', [AdminReactPosController::class, 'branches']);
        Route::post('/pos/branches', [AdminReactPosController::class, 'createBranch']);
        Route::post('/pos/branches/{id}/select', [AdminReactPosController::class, 'selectBranch'])->whereNumber('id');
        Route::post('/pos/cart/add', [AdminReactPosController::class, 'addCart']);
        Route::post('/pos/cart/increment', [AdminReactPosController::class, 'incrementCart']);
        Route::post('/pos/cart/decrement', [AdminReactPosController::class, 'decrementCart']);
        Route::post('/pos/cart/remove', [AdminReactPosController::class, 'removeCart']);
        Route::post('/pos/totals', [AdminReactPosController::class, 'setTotals']);
        Route::get('/pos/customer/search', [AdminReactPosController::class, 'searchCustomer']);
        Route::post('/pos/customer/save', [AdminReactPosController::class, 'saveCustomer']);
        Route::post('/pos/order/place', [AdminReactPosController::class, 'placeOrder']);
        Route::post('/pos/hold/save', [AdminReactPosController::class, 'holdSave']);
        Route::get('/pos/hold/{id}', [AdminReactPosController::class, 'holdDetails'])->whereNumber('id');
        Route::delete('/pos/hold/{id}', [AdminReactPosController::class, 'holdDelete'])->whereNumber('id');
        Route::post('/pos/hold/{id}/restore', [AdminReactPosController::class, 'holdRestore'])->whereNumber('id');
        Route::get('/design/themes', [AdminReactDesignController::class, 'themes']);
        Route::post('/design/themes/{id}/activate', [AdminReactDesignController::class, 'activateTheme'])->whereNumber('id');
        Route::get('/design/header-settings', [AdminReactDesignController::class, 'headerSettings']);
        Route::post('/design/header-settings', [AdminReactDesignController::class, 'saveHeaderSettings']);
        Route::get('/design/layout-sections', [AdminReactDesignController::class, 'layoutSections']);
        Route::get('/design/homepage-preview', [AdminReactDesignController::class, 'homepagePreview']);
        Route::post('/design/layout-sections/reorder', [AdminReactDesignController::class, 'reorderLayoutSections']);
        Route::get('/design/testimonials', [AdminReactDesignController::class, 'testimonials']);
        Route::post('/design/testimonials', [AdminReactDesignController::class, 'testimonialStore']);
        Route::post('/design/testimonials/{id}', [AdminReactDesignController::class, 'testimonialUpdate'])->whereNumber('id');
        Route::delete('/design/testimonials/{id}', [AdminReactDesignController::class, 'testimonialDelete'])->whereNumber('id');
        Route::get('/design/pages', [AdminReactDesignController::class, 'pages']);
        Route::post('/design/pages', [AdminReactDesignController::class, 'pageStore']);
        Route::post('/design/pages/{id}', [AdminReactDesignController::class, 'pageUpdate'])->whereNumber('id');
        Route::delete('/design/pages/{id}', [AdminReactDesignController::class, 'pageDelete'])->whereNumber('id');
        Route::get('/design/invoice-templates', [AdminReactDesignController::class, 'invoiceTemplates']);
        Route::post('/design/invoice-templates/{id}/activate', [AdminReactDesignController::class, 'activateInvoiceTemplate'])->whereNumber('id');
    });
});

Route::get('/{path?}', function () {
    $index = public_path('index.html');
    if (!is_file($index)) {
        abort(404);
    }

    return response()->file($index);
})->where('path', '^(?!react-admin-api|api|sanctum).*$');
